### ISSUE TITLE
Sample Code for Create PLY or Mesh from latents

### ISSUE THREAD

**Issue by AmanKishore** [openai/shap-e#1]
Hi, great job!
Shap-e looks much better than Point-E. Impressive work!

Do you have sample code that takes the latents and creates, ply and obj files?

Thank you!

**Comment by joinity** [comment]
Yeah seems like they must have! "Open" AI strikes again. Well at least they delivered this! :) Let's hope this will gain traction, could be really nice for cell shaded anime 3d worlds

**Comment by unixpickle** [comment]
I've pushed an example to the `sample_text_to_3d.ipynb` notebook in this commit: 8625e7c

```python
# Example of saving the latents as meshes.
from shap_e.util.notebooks import decode_latent_mesh

for i, latent in enumerate(latents):
    with open(f'example_mesh_{i}.ply', 'wb') as f:
        decode_latent_mesh(xm, latent).tri_mesh().write_ply(f)
```
