### ISSUE TITLE
Colab Directory Path Issue with image to 3d. 

### ISSUE THREAD

**Issue by zatamite** [openai/shap-e#10]
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-18-4db24f5a4c25>](https://localhost:8080/#) in <cell line: 4>()
      2 guidance_scale = 3.0
      3 
----> 4 image = load_image("example_data/corgi.png")
      5 
      6 latents = sample_latents(

2 frames
[/usr/local/lib/python3.10/dist-packages/blobfile/_context.py](https://localhost:8080/#) in BlobFile(self, path, mode, streaming, buffer_size, cache_dir, file_size, version)
    919                 raise Error("Cannot specify cache_dir for streaming files")
    920             if _is_local_path(path):
--> 921                 f = io.FileIO(path, mode=mode)
    922                 if "r" in mode:
    923                     f = io.BufferedReader(f, buffer_size=buffer_size)

FileNotFoundError: [Errno 2] No such file or directory: 'example_data/corgi.png'

**Comment by rishabhjain** [comment]
You need to upload an image and add it's path there.

**Comment by woctezuma** [comment]
Clone the directory or get the images from https://github.com/openai/shap-e/tree/main/shap_e/examples/example_data

**Comment by zatamite** [comment]
Nice.  Thanks.
