### ISSUE TITLE
Problems with encode_model

### ISSUE THREAD

**Issue by 1341828568** [openai/shap-e#107]
thank you for the excellent work!
I have a problem with encode_model.
I ran  encode_model.ipynb, and whenever I input a colored mesh ply file or obj file with mtl and texture(have been scaled and posed same as models generated by shap-e), it outputs strange things.
i use 'decode_latent_mesh' and it generates only three vertices, and nerf  renders nothing.
but there are no problems with text conditioned generation.
thanks for the help!

**Comment by 1341828568** [comment]
And pictures rendeedr by blender is so dark.
left is model in meshlab, right is render by blender.
<img width="453" alt="image" src="https://github.com/openai/shap-e/assets/47429765/bc25ec7b-c186-4d4e-acab-a10e13906587">

Is it correct?

**Comment by 1341828568** [comment]
output mesh in meshlab shows that it contains three vertices，but In fact, it looks like this：
<img width="209" alt="image" src="https://github.com/openai/shap-e/assets/47429765/e4cf51d4-996a-4ebf-a122-8d752ca312c1">

**Comment by 1341828568** [comment]
I changed my blender version from 3.6.0 to 3.4.1 and it workd.

**Comment by HaiderSaleem** [comment]
> I changed my blender version from 3.6.0 to 3.4.1 and it workd.

Hi,

Can you please help me with the following error:

` [90](file:///C:/Users/../blender/render.py:90)         raise RuntimeError(f"render failed: output file missing")
     [91](file:///C:/Users.../blender/render.py:91)     else:
     [92](file:///C:/Users/.../Anaconda3/envs/shap/Lib/site-packages/shap_e/rendering/blender/render.py:92)         raise RuntimeError(f"render failed: output file missing. Output: {output}")`
