### ISSUE TITLE
TypeError: Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by Dex-C** [openai/shap-e#12]
The error log I got:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/fr/8sx4p38j5394tjt8yg670kzm0000gn/T/ipykernel_61680/1008383796.py in <module>
----> 1 xm = load_model('transmitter', device=device)
      2 model = load_model('text300M', device=device)
      3 diffusion = diffusion_from_config(load_config('diffusion'))

~/Desktop/shap-e/shap_e/models/download.py in load_model(model_name, device, **kwargs)
    142     **kwargs,
    143 ) -> Dict[str, torch.Tensor]:
--> 144     from .configs import model_from_config
    145 
    146     model = model_from_config(load_config(model_name, **kwargs), device=device)

~/Desktop/shap-e/shap_e/models/configs.py in <module>
     16     UpsamplePointDiffusionTransformer,
     17 )
---> 18 from shap_e.models.nerf.model import MLPNeRFModel, VoidNeRFModel
     19 from shap_e.models.nerf.renderer import OneStepNeRFRenderer, TwoStepNeRFRenderer
     20 from shap_e.models.nerstf.mlp import MLPDensitySDFModel, MLPNeRSTFModel

~/Desktop/shap-e/shap_e/models/nerf/model.py in <module>
      8 
      9 from shap_e.models.nn.checkpoint import checkpoint
---> 10 from shap_e.models.nn.encoding import encode_position, spherical_harmonics_basis
     11 from shap_e.models.nn.meta import MetaModule, subdict
     12 from shap_e.models.nn.ops import MLP, MetaMLP, get_act, mlp_init, zero_init

~/Desktop/shap-e/shap_e/models/nn/encoding.py in <module>
    220     dtype: torch.dtype,
    221     device: torch.device,
--> 222 ) -> torch.Tensor:
    223     return 2.0 ** torch.arange(min_deg, max_deg, device=device, dtype=dtype)
    224 

~/opt/anaconda3/envs/peepee/lib/python3.7/functools.py in lru_cache(maxsize, typed)
    488             maxsize = 0
    489     elif maxsize is not None:
--> 490         raise TypeError('Expected maxsize to be an integer or None')
    491 
    492     def decorating_function(user_function):

I solved the issue by updating my Python from 3.7 to 3.11

**Comment by unixpickle** [comment]
Sounds like the issue was solved by updating Python. Glad to hear it!
