### ISSUE TITLE
Strange low cpu usage when sampling on cpu

### ISSUE THREAD

**Issue by 4eJIoBek1** [openai/shap-e#17]
Sampling on CPU is possible but takes about ~5% of overall computations, while 90% is free and not using and idk why.

**Comment by bavritzer** [comment]
Having a similar issue, it takes hours to sample from the 300M model using CPU as a result. Is there a smaller model we can access or some other fix?

**Comment by ibrahimsoliman97** [comment]
change  `use_fp16=False` in for sample_latents function, the speed i better on CPU for fp32, **this is not a root cause fix for low usage CPU.

**Comment by 4eJIoBek1** [comment]
OMG use_fp16=False is improves sampling speed dramatically! THX

- 2 times faster sampling on gpu
- 64 times faster sampling on cpu, with 20 steps you can make shapes for 10 minutes

anybody can explain why this setting is true by default? and why it works like this (imo sampling should be faster when fp16 precision is used, nor fp32 :/)
