### ISSUE TITLE
sample_text_to_3d jupyter notebook issue

### ISSUE THREAD

**Issue by michaelstrefeler** [openai/shap-e#33]
Hello,

I've installed shap-e on two computer now and I can't seem to get past the 4th code block on the notebook.

I haven't changed the code at all. It gets stuck on " 0% [insert empty progress bar here] 0/64 [00:00<?, ?it/s]". I had it running for over an hour and it didn't do anything.

How long is it supposed to take on average? Am I being impatient or is something wrong with my computers?

PS. I'm on Windows 11

**Comment by michaelstrefeler** [comment]
Once I added this issues the code started working. Sorry

**Comment by Nojahhh** [comment]
I experience the same thing on my installation. Doesn't give me any errors but my progress bar looks like yours and I have been letting it run for 120 minutes with nothing happening, so I'm assuming that it doesn't work, but I might be wrong. I'm on Windows 10 with an i9-9900K and 64GB DDR4, which makes me think that if it would work it would have moved atleast 1% in that time. What did you do to solve it?

**Comment by rk-exxec** [comment]
> Once I added this issues the code started working. Sorry

@michaelstrefeler What do you mean? Did you restart or just let it run for longer?

**Comment by michaelstrefeler** [comment]
> > Once I added this issues the code started working. Sorry
> 
> @michaelstrefeler What do you mean? Did you restart or just let it run for longer?

I ran it again without any changes and it worked

**Comment by michaelstrefeler** [comment]
> I experience the same thing on my installation. Doesn't give me any errors but my progress bar looks like yours and I have been letting it run for 120 minutes with nothing happening, so I'm assuming that it doesn't work, but I might be wrong. I'm on Windows 10 with an i9-9900K and 64GB DDR4, which makes me think that if it would work it would have moved atleast 1% in that time. What did you do to solve it?

Restarting the kernel might fix it. Restarting your computer could also help

**Comment by Kabanosk** [comment]
@Nojahhh I think you run it on CPU. For me, computation on CPU takes ~37h (i7 11gen) but on Google colab GPUs - around 2 minutes.
