### ISSUE TITLE
Typo in Figure2

### ISSUE THREAD

**Issue by hu-po** [openai/shap-e#37]
![image](https://user-images.githubusercontent.com/8493427/236855678-ecd377ac-4cb4-4508-81bf-db5b52695439.png)
I think this should be 60 views, not 20 right?

**Comment by unixpickle** [comment]
Actually, we condition the model on 20 views, but we generate point clouds with 60 views. This is a somewhat arbitrary choice, but we basically did it to limit the context length of the transformer.
