### ISSUE TITLE
why my render obj\ply text-conditional model is a blank model?  Can it have colored textures？

### ISSUE THREAD

**Issue by Bean95zx** [openai/shap-e#57]
why my render obj\ply text-conditional model is a blank model?  Can it have colored textures？
![image](https://github.com/openai/shap-e/assets/44997999/0dc02e92-0d24-4bed-9416-a9fbc9905bce)

**Comment by neurowelt** [comment]
Not sure if that solves your question, but in Blender by default objects are loaded in `Object Mode` which shows no textures. Switch to `Vertex Paint` to see the textures of your objects.

<img width="414" alt="Screenshot 2023-05-12 at 10 29 13" src="https://github.com/openai/shap-e/assets/29918691/9538732a-6cba-4cd5-b451-9fe02b3287c8">

**Comment by Bean95zx** [comment]
> 
thanks. it solve my problem.
