### ISSUE TITLE
Issue Report: TypeError in shap_e/examples/sample_text_to_3d.ipynb

### ISSUE THREAD

**Issue by HFarkhari** [openai/shap-e#58]
Dear OpenAI Support,

I hope this message finds you well. I encountered an issue while running the sample_text_to_3d.ipynb file from the shap-e-main repository. The error message I received was:

TypeError: "'type' object is not subscriptable"

After investigating the problem, I managed to find a solution. However, I believe it is important to report this issue and provide a suggestion for resolving it in the codebase.

The issue arises from the use of AttrDict with subscript notation ([]), which is not supported by the AttrDict class. To address this problem, I recommend replacing all instances of AttrDict[... with Dict[... in the relevant Python files. It is crucial to make this replacement only if you encounter [ immediately after AttrDict.

I would like to contribute to improving the codebase and help other users who might encounter the same error. Therefore, I wanted to bring this issue to your attention and kindly request that you update the affected code accordingly.

Thank you for your attention to this matter, and I appreciate your efforts in maintaining and enhancing the open-source projects.

Best regards,
Hamed Farkhari
[HFarkhari]

**Comment by xaranex1** [comment]
yes same mistake for me but in colab it works fine..
