### ISSUE TITLE
pytorch3d missing when using stf mode.

### ISSUE THREAD

**Issue by shamelesslyAI** [openai/shap-e#9]
Can anyone check for pytorch3d? whenever changing from "nerf" to "stf" it will error out with "No module named 'pytorch3d'". Having a hard time finding and installing the right version for Colab (the stable builds at https://github.com/facebookresearch/
[pytorch3d](https://github.com/facebookresearch/pytorch3d) hangs and doesn't install). 

![Screenshot 2023-05-05 at 13-02-22 Google Colaboratory](https://user-images.githubusercontent.com/82715097/236521958-ec8d6ff1-7b10-4170-8aae-28bf0d6352f2.png)

Thanks.

**Comment by unixpickle** [comment]
This should be fixed now, by https://github.com/openai/shap-e/commit/8b1010b9a66434603a83e1f932f308028e6158ce
